---
name: Build ISOs (Live)

on:
  workflow_dispatch:
    inputs:
      upload-to-cloudflare:
        description: "Upload to Cloudflare"
        required: false
        default: false
        type: boolean
  # schedule:
  #   - cron: "0 1 * * *"

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "bluefin"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISOs
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64]
        flavor: ["", "nvidia-open"]
        image_version: ["gts", "latest"]
        # include:
        #   - platform: amd64
        #     flavor: ""
        #     image_version: lts
        #   - platform: arm64
        #     flavor: ""
        #     image_version: lts
        #   - platform: amd64
        #     flavor: gdx
        #     image_version: lts
        #   - platform: arm64
        #     flavor: gdx
        #     image_version: lts
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Install dependencies
        if: matrix.platform == 'arm64'
        run: |
          set -euxo pipefail
          sudo apt update -y
          sudo apt install -y podman

      - name: Maximize build space
        if: matrix.platform != 'arm64'
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
        with:
          remove-codeql: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Format image ref
        id: image_ref
        env:
          FLAVOR: ${{ matrix.flavor }}
        run: |
          set -euxo pipefail
          OUTPUT_NAME="${IMAGE_REGISTRY}/${IMAGE_NAME}"
          ARTIFACT_FORMAT=""
          KARGS="NONE"
          if [ "$FLAVOR" != "" ] ; then
            OUTPUT_NAME="${OUTPUT_NAME}-${FLAVOR}"
            ARTIFACT_FORMAT="-${FLAVOR}"
            if [ "$FLAVOR" =~ nvidia ] ; then
              KARGS="rd.driver.blacklist=nouveau,modprobe.blacklist=nouveau"
              KARGS+=",nvidia-drm.modeset=1"
            fi
          fi
          echo "image_ref=$OUTPUT_NAME" >>"${GITHUB_OUTPUT}"
          echo "artifact_format=$ARTIFACT_FORMAT" >>"${GITHUB_OUTPUT}"
          echo "kargs=$KARGS" >>"${GITHUB_OUTPUT}"

      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@main
        with:
          image-ref: ${{ steps.image_ref.outputs.image_ref }}:${{ matrix.image_version }}
          flatpaks-list: ${{ github.workspace }}/build_files/iso/system-flatpaks.list
          hook-post-rootfs: ${{ github.workspace }}/build_files/iso/configure_iso.sh
          kargs: ${{ steps.image_ref.outputs.kargs }}

      - name: Rename ISO
        id: rename
        env:
          OUTPUT_PATH: ${{ steps.build.outputs.iso-dest }}
          FLAVOR: ${{ matrix.flavor }}
          ARTIFACT_FORMAT: ${{ steps.image_ref.outputs.artifact_format }}
          IMAGE_VERSION: ${{ matrix.image_version }}
        run: |
          set -euxo pipefail
          mkdir -p output
          OUTPUT_NAME="readymade-${IMAGE_NAME}${ARTIFACT_FORMAT}-${IMAGE_VERSION}"
          OUTPUT_DIRECTORY="$(realpath output)"
          if [[ "${FLAVOR}" != "" ]] ; then
            IMAGE_NAME="${IMAGE_NAME}-${FLAVOR}"
          fi
          sha256sum "${OUTPUT_PATH}" |
                tee "${OUTPUT_DIRECTORY}/${OUTPUT_NAME}-$(uname -m).iso-CHECKSUM"
          mv "${OUTPUT_PATH}" "${OUTPUT_DIRECTORY}/${OUTPUT_NAME}-$(uname -m).iso"
          echo "output_directory=$OUTPUT_DIRECTORY" >>"${GITHUB_OUTPUT}"

      - name: Upload to Job Artifacts
        if: inputs.upload-to-cloudflare == false || github.event_name == 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.IMAGE_NAME }}-live${{ steps.image_ref.outputs.artifact_format }}-${{ matrix.image_version }}-${{ matrix.platform }}-iso
          if-no-files-found: error
          path: ${{ steps.rename.outputs.output_directory }}

      - name: Upload to CloudFlare
        if: inputs.upload-to-cloudflare == true && github.event_name != 'pull_request'
        shell: bash
        env:
          RCLONE_CONFIG_S3_TYPE: s3
          RCLONE_CONFIG_S3_PROVIDER: ${{ secrets.S3_PROVIDER }}
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_S3_REGION: ${{ secrets.S3_REGION }}
          RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          SOURCE_DIR: ${{ steps.rename.outputs.output_directory }}
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copy "${SOURCE_DIR}" R2:bluefin